params:
    - sigma: 0.1
      lambda_: 0.1
    - sigma: 0.1
      lambda_: 1.0
    - sigma: 0.1
      lambda_: 10.0
    - sigma: 1.0
      lambda_: 0.1
    - sigma: 1.0
      lambda_: 1.0
    - sigma: 1.0
      lambda_: 10.0
    - sigma: 10.0
      lambda_: 0.1
    - sigma: 10.0
      lambda_: 1.0
    - sigma: 10.0
      lambda_: 10.0